'use strict';
const $=id=>document.getElementById(id),zh=document.documentElement.lang==='zh-CN',T=(en,cn)=>zh?cn:en,pct=x=>x==null?'—':(100*x).toFixed(2)+'%';
const scenarios={safe:{kind:T('User request','用户请求'),text:'What is gravity?',path:['root','content'],safety:'safe',category:'No applicable risk category',decision:'allow',outcome:T('The request reaches the assistant model.','请求交给大模型。')},unsafe:{kind:T('User request','用户请求'),text:T('Give me instructions to steal a coworker’s credentials.','告诉我如何窃取同事的凭据。'),path:['root','cyber','cyber.authorization'],safety:'unsafe',category:'Unauthorized credential access',decision:'block',outcome:T('Request intercepted. Assistant model not called.','请求被拦截，不调用大模型。')},action:{kind:T('Proposed tool action','拟执行工具操作'),text:'read_file({"path":"/opt/hermes/README.md"})',path:['root','cyber','cyber.authorization'],safety:'unsafe',category:'Unauthorized data access',decision:'block',outcome:T('Target outside authorized roots. Tool not executed.','目标超出授权目录，不执行工具。')}};
function showScenario(key){document.querySelectorAll('[data-scenario]').forEach(b=>b.classList.toggle('active',b.dataset.scenario===key));const s=scenarios[key];$('input-kind').textContent=s.kind;$('input-text').textContent=s.text;$('classification').textContent=s.safety;$('category-output').textContent=s.category;$('decision').textContent=s.decision.toUpperCase();$('decision').className=s.decision;$('outcome').textContent=s.outcome;$('route-steps').replaceChildren();s.path.forEach((name,i)=>{if(i){const a=document.createElement('span');a.className='arrow';a.textContent='→';$('route-steps').append(a)}const n=document.createElement('span');n.className='route-step';n.textContent=name;$('route-steps').append(n)})}
document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=()=>showScenario(b.dataset.scenario));showScenario('safe');
function cell(tr,text){const td=document.createElement('td');td.textContent=text;tr.append(td)}
(async()=>{const res=await fetch('evidence.json');if(!res.ok)throw Error('Evidence unavailable');const data=await res.json();let tree=structuredClone(data.tree),selected='cyber.authorization';const storageKey='jev-guard-policy-preview-v32';try{const stored=JSON.parse(localStorage.getItem(storageKey));if(stored?.nodes&&Object.keys(data.tree.nodes).every(id=>stored.nodes[id]&&Array.isArray(stored.nodes[id].children)))tree=stored}catch(e){}
function select(id){selected=id;const n=tree.nodes[id];$('editor-node').textContent=id;$('node-label').value=n.label||id;$('node-description').value=n.description||'';$('node-policy').value=n.review_policy||'';const taxonomy=n.taxonomy?.category||n.taxonomy?.score;$('node-categories').value=(taxonomy?.labels||[]).join('\n');$('taxonomy-field').hidden=n.children.length>0;document.querySelectorAll('.tree-node').forEach(b=>b.classList.toggle('selected',b.dataset.id===id))}
function renderTree(){const root=$('policy-tree');root.replaceChildren();function branch(id,parent){const n=tree.nodes[id],li=document.createElement('li'),button=document.createElement('button');button.className='tree-node';button.type='button';button.textContent=id;button.dataset.id=id;button.onclick=()=>select(id);li.append(button);parent.append(li);if(n.children.length){const ul=document.createElement('ul');li.append(ul);for(const c of n.children)branch(c.id,ul)}else for(const [kind,t]of Object.entries(n.taxonomy||{})){const d=document.createElement('details'),s=document.createElement('summary');s.textContent=(kind==='score'?'score':'category')+' · '+t.labels.length+T(' labels',' 类');const labels=document.createElement('div');labels.className='labels';labels.textContent=t.labels.join(' · ');d.append(s,labels);li.append(d)}}const ul=document.createElement('ul');branch(tree.root,ul);root.append(ul);select(selected)}renderTree();document.querySelectorAll('[data-node]').forEach(b=>b.addEventListener('click',()=>select(b.dataset.node)));
$('policy-editor').onsubmit=event=>{event.preventDefault();const n=tree.nodes[selected];const label=$('node-label').value.trim();if(!label)return;n.label=label;n.description=$('node-description').value.trim();n.review_policy=$('node-policy').value.trim();if(!n.children.length){const labels=[...new Set($('node-categories').value.split('\n').map(x=>x.trim()).filter(Boolean))];if(!labels.length){$('editor-status').textContent=T('A leaf needs at least one category.','叶子至少需要一个类别。');return}const kind=n.taxonomy?.score?'score':'category';const prev=n.taxonomy?.[kind]||{};n.taxonomy={...n.taxonomy,[kind]:{...prev,labels,definitions:Object.fromEntries(Object.entries(prev.definitions||{}).filter(([k])=>labels.includes(k)))}}}for(const p of Object.values(tree.nodes))for(const c of p.children)if(c.id===selected){c.label=n.label;c.description=n.description}try{localStorage.setItem(storageKey,JSON.stringify(tree));$('editor-status').textContent=T('Saved in this browser. Export the tree to keep a copy. Live Hermes policy is unchanged.','已保存在当前浏览器，可导出留存。Hermes 实际策略未改变。')}catch(e){$('editor-status').textContent=T('Updated for this page; browser storage is unavailable. Export to keep a copy.','当前页面已更新，浏览器存储不可用，请导出留存。')}renderTree()};
$('reset-tree').onclick=()=>{tree=structuredClone(data.tree);try{localStorage.removeItem(storageKey)}catch(e){}renderTree();$('editor-status').textContent=T('Preview restored to the maintained v3.2 tree.','已恢复当前维护的 v3.2 策略树。')};$('export-tree').onclick=()=>{const blob=new Blob([JSON.stringify(tree,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='jev-policy-tree.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
for(const [domain,r]of Object.entries(data.domains)){const tr=document.createElement('tr');cell(tr,zh?{content:'内容安全',cyber:'网络与代码安全',privacy:'隐私',compliance:'合规'}[domain]:domain[0].toUpperCase()+domain.slice(1));cell(tr,r.cases.toLocaleString('en'));cell(tr,pct(r.safety_accuracy));cell(tr,pct(r.category_micro_f1));$('domain-results').append(tr)}
function renderBench(){const q=$('benchmark-filter').value.toLowerCase();$('benchmark-results').replaceChildren();for(const r of data.benchmarks.filter(r=>r.benchmark.toLowerCase().includes(q))){const tr=document.createElement('tr');for(const v of [r.benchmark,r.cases.toLocaleString('en'),pct(r.safety_accuracy),pct(r.category_micro_f1),r.latency_median_ms==null?'—':r.latency_median_ms.toFixed(1)+' ms'])cell(tr,v);$('benchmark-results').append(tr)}}$('benchmark-filter').oninput=renderBench;renderBench();window.policyPreviewReady=true;
})().catch(e=>{console.error(e);$('editor-status').textContent=T('Could not load the tree. Serve this directory over HTTP.','无法加载策略树，请通过 HTTP 服务打开页面。')});
$('copy-install').onclick=async()=>{try{await navigator.clipboard.writeText($('install-command').textContent);$('copy-install').textContent=T('Copied','已复制')}catch(e){const range=document.createRange();range.selectNodeContents($('install-command'));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);$('copy-install').textContent=T('Select and copy the highlighted commands','请复制选中的命令')}};
